<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 2019-03-01
 * Time: 14:09
 */

class WishlistWishlistModuleFrontController extends ModuleFrontController
{
    public $auth = true;


    public function __construct()
    {
        parent::__construct();
        $this->authRedirection =  $this->context->link->getModuleLink('wishlistObject', 'wishlistObject');
    }

    public function init(){
        $this->page_name = 'wishlistObject';

        parent::init();
    }

    public function initContent()
    {
        parent::initContent();
        $this->setTemplate('module:wishlist/views/templates/front/test.tpl');
        $this->context->link->getModuleLink('wishlistObject', 'wishlistObject');

//        if (!$this->context->customer->isLogged() && $this->php_self != 'authentication' && $this->php_self != 'password') {
//
//            Tools::redirect('index.php?controller=authentication?back=my-account');
//        }
    }


    public function postProcess()
    {
        parent::postProcess(); // TODO: Change the autogenerated stub

        $id = null;
        if(Tools::isSubmit('submit_wishlist')){
            if ($this->context->customer->isLogged()) {
                echo  $id=(int)$this->context->customer->id;
            }
        }
    }

    public function assign()
    {
        $wishlistObject = new wishlistObject();
        $id_customer =null;
        $id_product = Tools::getValue('id_product');

        if ($this->context->customer->isLogged())
        {
            $id_customer =(int)$this->context->customer->id;
        }
        $wishlistObject->addProduct($id_product,$id_customer);
    }
}
